package com.lwf.mapper;

import com.lwf.pojo.Students;
import com.lwf.pojo.StudentsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int countByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int deleteByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int insertSelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    List<Students> selectByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    Students selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") Students record, @Param("example") StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int updateByExample(@Param("record") Students record, @Param("example") StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int updateByPrimaryKeySelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STUDENTS
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    int updateByPrimaryKey(Students record);
}