package com.lwf.pojo;

public class Students {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENTS.ID
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    private Short id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENTS.NAME
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENTS.SEX
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENTS.CNO
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    private String cno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENTS.ID
     *
     * @return the value of STUDENTS.ID
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENTS.ID
     *
     * @param id the value for STUDENTS.ID
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENTS.NAME
     *
     * @return the value of STUDENTS.NAME
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENTS.NAME
     *
     * @param name the value for STUDENTS.NAME
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENTS.SEX
     *
     * @return the value of STUDENTS.SEX
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENTS.SEX
     *
     * @param sex the value for STUDENTS.SEX
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENTS.CNO
     *
     * @return the value of STUDENTS.CNO
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public String getCno() {
        return cno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENTS.CNO
     *
     * @param cno the value for STUDENTS.CNO
     *
     * @mbggenerated Sat Nov 07 10:01:00 CST 2020
     */
    public void setCno(String cno) {
        this.cno = cno;
    }
}